<a href="https://colab.research.google.com/github/niginadavronova/collab.works/blob/main/_numpyassign_2_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)

# **DATA SCIENCE VA SUN'IY INTELLEKT PRAKTIKUM**

## Ma'lumotlar tahlili. Numpy kutubxonasi.

# **2-AMALIY VAZIFA**

## N-o'lchamli massivlarga ishov berish

In [ ]:
# Numpy kutubxonasini chaqirib olish
import numpy as np

### Masala(1): 2-o'lchamli massiv yaratish

**Masala sharti :** Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv yaratuvchi funksiyani davom ettiring.  

**Yordam :**  `arange`dan foydalanish ishni osonlashtiradi


In [ ]:
# JAVOBNI SHU YERGA YOZING
arr=np.arange(0,9,1)
arr=arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Yuqoridagi yozgan funksiyangizni tekshirish uchun, quyidagi cellni yuriting.

___

###  Masala(2): Indeks yordamida 2-o'lchamli massivlardan elementlarni  kesib olish
**Masala :** Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan qismini kesib olish funksiyasini davom ettiring.

**Yordam :** 6 va 7 turgan indekslarni aniqlab olib, shu indekslar yordamida kesib oling. **Natija:** array([6, 7]) ko'rinishida bo'lishi kerak.

In [ ]:
# JAVOBNI SHU YERGA YOZING
sliced_arr=arr[2,:2]
sliced_arr
#array = nd_array() # yuqoridagi funksiya yordamida array yaratib olish

array([6, 7])

### Yuqoridagi yozgan funksiyangizni tekshirish uchun, quyidagi cellni yuriting.

___

###  Masala(3): Indeks yordamida 3-o'lchamli massivdan elementlarni kesib olish

**Masala :**  3-o'lchamli massivni quyidagi listdan yarating, hamda 12, 13, 15, va 16  elementlarini kesib oluvchi funksiyani davom ettiring.  

                  [[[ 0,  1,  2],
                    [ 3,  4,  5],
                    [ 6,  7,  8]],

                   [[ 9, 10, 11],
                    [12, 13, 14],
                    [15, 16, 17]],

                   [[18, 19, 20],
                    [21, 22, 23],
                    [24, 25, 26]]]

**Yordam :** Avval massivni ikki o'lchamli massivga keltirib, keyin kesib olishni amalga oshiring.


**Natija:**  

             array([[12, 13],
                    [15, 16]])
ko'rinishida bo'lishi kerak.

In [ ]:
arr3=np.arange(0,27,1)
arr3=arr3.reshape(3,3,3)
arr3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
arr3[1][1:,:2]

array([[12, 13],
       [15, 16]])

###  Masala(4): Boolean indeks yordamida 2 o'lchamli massivlardan elementlarni  kesib olish

**Masala :** Bizlarda,  
        
        ['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor']

**list**dagi kishilar va ularning **ma'lumot**lari
       
      [[5, 6, 1, 1],
       [9, 1, 1, 1],
       [7, 7, 4, 2],
       [1, 5, 1, 9],
       [9, 9, 4, 5],
       [7, 5, 9, 6],
       [5, 3, 7, 4]]
ko'rinishda keltirilgan.


Mana shu ma'lumotlardan **Javohir** va **Elyor** ismlariga tegishli ma'lumotlarni Boolean indekslash yordamida kesib olish funksiyasini davom ettiring.
**Yordam :** Boolean indekslash video darsligiga murojat qiling.
**Natija:** Natija (4, 4) o'lchamli massiv ko'rinishida, hamda dastlabki ikkita qatori quyidagicha

    array([[7, 7, 4, 2],
           [1, 5, 1, 9],
           ...
           ...        ]])

In [ ]:
names=np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U7')

In [ ]:
data=np.random.randn(7,4)
data

array([[-0.36866062,  1.82533476, -0.54125145,  0.24294898],
       [-0.04380263,  0.58449551,  0.24857809, -0.17967201],
       [-0.44681911, -0.66554684, -0.25846313,  0.16474938],
       [-0.94435056,  1.11835748, -2.38309186, -0.21325812],
       [-0.3367029 ,  0.34610585,  0.61141795, -1.00058843],
       [ 0.27228862, -0.1720813 ,  0.0273572 ,  1.78687136],
       [-0.08089669,  0.29837041,  0.67420291,  0.70166925]])

In [ ]:
names=='Elyor'

array([False, False, False,  True, False, False,  True])

In [ ]:
names=='Javohir'

array([False, False,  True, False, False,  True, False])

In [ ]:
data[names=='Javohir']

array([[-0.44681911, -0.66554684, -0.25846313,  0.16474938],
       [ 0.27228862, -0.1720813 ,  0.0273572 ,  1.78687136]])

In [ ]:
data[names=='Elyor']

array([[-0.94435056,  1.11835748, -2.38309186, -0.21325812],
       [-0.08089669,  0.29837041,  0.67420291,  0.70166925]])

In [ ]:
mask=(names=='Elyor')|(names=='Javohir')
data[mask]

array([[-0.44681911, -0.66554684, -0.25846313,  0.16474938],
       [-0.94435056,  1.11835748, -2.38309186, -0.21325812],
       [ 0.27228862, -0.1720813 ,  0.0273572 ,  1.78687136],
       [-0.08089669,  0.29837041,  0.67420291,  0.70166925]])