<a href="https://colab.research.google.com/github/niginadavronova/collab.works/blob/main/NumPy_where_logical_set_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili.
## 2.1. NumPy kutubxonasi bilan ishlash

### NumPy kutubxonasini chaqirib olish

In [ ]:
import numpy as np

### 2.1.3. Massivga yo'naltirilgan dasturlash

### Mantiqiy shart operatorlarni massiv operator sifatida qo'llash

### Shart operatori sifatida `where` dan foydalanish

### Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular: `xarr` va `yarr`. Agarda shart `True`ni qanoatlantirsa `xarr` elementini qabul qilgan aksincha esa `yarr` elementini qabul qilgan yangi massiv hosil qilinsin.

In [ ]:
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr

In [ ]:
# Shart
cond = np.array([True, False, True, True, False])

In [ ]:
# where
result = np.where(cond, xarr, yarr) # cond==True : xarr elementi, cond==False : yarr elementi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
arr = np.random.randn(4, 4)  # (4, 4) taxminiy massiv
arr

array([[ 0.20872063,  0.58371546, -0.58103378, -0.05381021],
       [-0.84436484, -0.52853447,  1.18669295, -0.9426822 ],
       [ 0.6948761 ,  0.36436058,  0.83384314, -0.43226105],
       [-0.41051829, -2.23680132, -0.51540911,  0.60118055]])

In [ ]:
# where
results = np.where(arr<0, -2, 2) # arr ning manfiy elementlarini -2 ga musbat elementlarin esa 2 ga almashitirish
results

array([[ 2,  2, -2, -2],
       [-2, -2,  2, -2],
       [ 2,  2,  2, -2],
       [-2, -2, -2,  2]])

Bonus hisoblash (np.where bilan):

Kompaniya staji 5 yil va undan yuqori bo'lgan xodimlarga 500$ bonus, staji 5 yildan kam bo'lganlarga esa 100$ bonus berishga qaror qildi.

np.where yordamida har bir xodim oladigan bonus miqdorini hisoblab, bonuslar massiviga saqlang.

In [ ]:
staj=np.array([1, 4, 7, 2,8, 3, 6, 10, 0.5, 5])

In [ ]:
maosh = np.array([800, 1500, 2200, 950, 2800, 1200, 2000, 3200, 600, 1800])

In [ ]:
bonus = np.where(staj>=5,500, 100)
bonus

array([100, 100, 500, 100, 500, 100, 500, 500, 100, 500])

Yangi maoshni shakllantirish:

Ish staji 4 yildan ko'p bo'lgan xodimlarning maoshini 15% ga oshiring, qolgan xodimlarning maoshini esa o'zgarishsiz (0% oshirish) qoldiring.

np.where yordamida barcha xodimlarning yangi oylik maoshini hisoblang (yangi_maosh massivi).

In [ ]:
yangi_maosh = np.where(staj>4, maosh * 1.15, maosh)
yangi_maosh

array([ 800., 1500., 2530.,  950., 3220., 1200., 2300., 3680.,  600.,
       2070.])

Kombinatsiyalangan (Murakkab) shart:

Kompaniya maoshi 1500$ dan kam bo'lgan VA staji 2 yildan ko'p bo'lgan xodimlarga "Rag'batlantirish zarur", qolgan barchaga "O'z joyida" degan status berishi kerak.

Ushbu shart bo'yicha np.where yordamida xodimlarning statuslarini aniqlang (status massivi).


In [ ]:
status = np.where((staj>2) & (maosh<1500), "Rag'batlantirish zarur", "O'z joyida qolsin")
status

array(["O'z joyida qolsin", "O'z joyida qolsin", "O'z joyida qolsin",
       "O'z joyida qolsin", "O'z joyida qolsin", "Rag'batlantirish zarur",
       "O'z joyida qolsin", "O'z joyida qolsin", "O'z joyida qolsin",
       "O'z joyida qolsin"], dtype='<U22')

4-topshiriq: To'g'ridan-to'g'ri massiv o'rniga massivni almashtirish (YOKI / OR sharti)
Kompaniya ba'zi xodimlarning maoshiga tayyor belgilangan ustamani ko'tarib bermoqchi.

Shart: Agar xodimning staji 8 yildan ko'p YOKI maoshi 3000$ dan yuqori bo'lsa, ularga maxsus premium ustamalarni (premium massividan) qo'shib bering. Qolganlarga esa oddiy 200$ ustama bering.

In [ ]:
premium = np.array([500, 500, 600, 500, 700, 500, 600, 800, 500, 600])

In [ ]:
ustama = np.where((staj>8)|(maosh>3000), premium, 200)
ustama

array([200, 200, 200, 200, 200, 200, 200, 800, 200, 200])

5-topshiriq: Ichma-ich np.where (Nested np.where)
Ba'zan shartlar 2 tadan ko'p bo'ladi (masalan: "Aks holda, agar..."). np.where funksiyasining yarr (False bo'lganda) qismiga yana bitta np.where yozib, uch bosqichli kategoriya tuzing.

Shart:

Staji 7 yildan ko'p bo'lsa -> "Senior"

Staji 3 dan 7 gacha bo'lsa -> "Middle"

Staji 3 yildan kam bo'lsa -> "Junior"

Vazifa: Yagona kod satrida ichma-ich np.where ishlatib, barcha xodimlarning darajasini (daraja massivi) aniqlang.

In [ ]:
daraja=np.where(staj>7, "Senior", np.where(staj>=3, "Middle", "Junior"))
daraja

array(['Junior', 'Middle', 'Middle', 'Junior', 'Senior', 'Middle',
       'Middle', 'Senior', 'Junior', 'Middle'], dtype='<U6')